/**
 * Autogenerated by Thrift Compiler (0.9.3)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package liker;

import org.apache.thrift.scheme.IScheme;
import org.apache.thrift.scheme.SchemeFactory;
import org.apache.thrift.scheme.StandardScheme;

import org.apache.thrift.scheme.TupleScheme;
import org.apache.thrift.protocol.TTupleProtocol;
import org.apache.thrift.protocol.TProtocolException;
import org.apache.thrift.EncodingUtils;
import org.apache.thrift.TException;
import org.apache.thrift.async.AsyncMethodCallback;
import org.apache.thrift.server.AbstractNonblockingServer.*;
import java.util.List;
import java.util.ArrayList;
import java.util.Map;
import java.util.HashMap;
import java.util.EnumMap;
import java.util.Set;
import java.util.HashSet;
import java.util.EnumSet;
import java.util.Collections;
import java.util.BitSet;
import java.nio.ByteBuffer;
import java.util.Arrays;
import javax.annotation.Generated;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

@SuppressWarnings({"cast", "rawtypes", "serial", "unchecked"})
@Generated(value = "Autogenerated by Thrift Compiler (0.9.3)", date = "2018-01-23")
public class IndexTask implements org.apache.thrift.TBase<IndexTask, IndexTask._Fields>, java.io.Serializable, Cloneable, Comparable<IndexTask> {
  private static final org.apache.thrift.protocol.TStruct STRUCT_DESC = new org.apache.thrift.protocol.TStruct("IndexTask");

  private static final org.apache.thrift.protocol.TField TYPE_FIELD_DESC = new org.apache.thrift.protocol.TField("type", org.apache.thrift.protocol.TType.I32, (short)1);
  private static final org.apache.thrift.protocol.TField DOC_FIELD_DESC = new org.apache.thrift.protocol.TField("doc", org.apache.thrift.protocol.TType.STRUCT, (short)2);
  private static final org.apache.thrift.protocol.TField TARGET_FIELD_FIELD_DESC = new org.apache.thrift.protocol.TField("targetField", org.apache.thrift.protocol.TType.STRUCT, (short)3);

  private static final Map<Class<? extends IScheme>, SchemeFactory> schemes = new HashMap<Class<? extends IScheme>, SchemeFactory>();
  static {
    schemes.put(StandardScheme.class, new IndexTaskStandardSchemeFactory());
    schemes.put(TupleScheme.class, new IndexTaskTupleSchemeFactory());
  }

  /**
   * 
   * @see IndexTaskType
   */
  public IndexTaskType type; // required
  public Document doc; // required
  public Field targetField; // required

  /** The set of fields this struct contains, along with convenience methods for finding and manipulating them. */
  public enum _Fields implements org.apache.thrift.TFieldIdEnum {
    /**
     * 
     * @see IndexTaskType
     */
    TYPE((short)1, "type"),
    DOC((short)2, "doc"),
    TARGET_FIELD((short)3, "targetField");

    private static final Map<String, _Fields> byName = new HashMap<String, _Fields>();

    static {
      for (_Fields field : EnumSet.allOf(_Fields.class)) {
        byName.put(field.getFieldName(), field);
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, or null if its not found.
     */
    public static _Fields findByThriftId(int fieldId) {
      switch(fieldId) {
        case 1: // TYPE
          return TYPE;
        case 2: // DOC
          return DOC;
        case 3: // TARGET_FIELD
          return TARGET_FIELD;
        default:
          return null;
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, throwing an exception
     * if it is not found.
     */
    public static _Fields findByThriftIdOrThrow(int fieldId) {
      _Fields fields = findByThriftId(fieldId);
      if (fields == null) throw new IllegalArgumentException("Field " + fieldId + " doesn't exist!");
      return fields;
    }

    /**
     * Find the _Fields constant that matches name, or null if its not found.
     */
    public static _Fields findByName(String name) {
      return byName.get(name);
    }

    private final short _thriftId;
    private final String _fieldName;

    _Fields(short thriftId, String fieldName) {
      _thriftId = thriftId;
      _fieldName = fieldName;
    }

    public short getThriftFieldId() {
      return _thriftId;
    }

    public String getFieldName() {
      return _fieldName;
    }
  }

  // isset id assignments
  public static final Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> metaDataMap;
  static {
    Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> tmpMap = new EnumMap<_Fields, org.apache.thrift.meta_data.FieldMetaData>(_Fields.class);
    tmpMap.put(_Fields.TYPE, new org.apache.thrift.meta_data.FieldMetaData("type", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.EnumMetaData(org.apache.thrift.protocol.TType.ENUM, IndexTaskType.class)));
    tmpMap.put(_Fields.DOC, new org.apache.thrift.meta_data.FieldMetaData("doc", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.StructMetaData(org.apache.thrift.protocol.TType.STRUCT, Document.class)));
    tmpMap.put(_Fields.TARGET_FIELD, new org.apache.thrift.meta_data.FieldMetaData("targetField", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.StructMetaData(org.apache.thrift.protocol.TType.STRUCT, Field.class)));
    metaDataMap = Collections.unmodifiableMap(tmpMap);
    org.apache.thrift.meta_data.FieldMetaData.addStructMetaDataMap(IndexTask.class, metaDataMap);
  }

  public IndexTask() {
  }

  public IndexTask(
    IndexTaskType type,
    Document doc,
    Field targetField)
  {
    this();
    this.type = type;
    this.doc = doc;
    this.targetField = targetField;
  }

  /**
   * Performs a deep copy on <i>other</i>.
   */
  public IndexTask(IndexTask other) {
    if (other.isSetType()) {
      this.type = other.type;
    }
    if (other.isSetDoc()) {
      this.doc = new Document(other.doc);
    }
    if (other.isSetTargetField()) {
      this.targetField = new Field(other.targetField);
    }
  }

  public IndexTask deepCopy() {
    return new IndexTask(this);
  }

  @Override
  public void clear() {
    this.type = null;
    this.doc = null;
    this.targetField = null;
  }

  /**
   * 
   * @see IndexTaskType
   */
  public IndexTaskType getType() {
    return this.type;
  }

  /**
   * 
   * @see IndexTaskType
   */
  public IndexTask setType(IndexTaskType type) {
    this.type = type;
    return this;
  }

  public void unsetType() {
    this.type = null;
  }

  /** Returns true if field type is set (has been assigned a value) and false otherwise */
  public boolean isSetType() {
    return this.type != null;
  }

  public void setTypeIsSet(boolean value) {
    if (!value) {
      this.type = null;
    }
  }

  public Document getDoc() {
    return this.doc;
  }

  public IndexTask setDoc(Document doc) {
    this.doc = doc;
    return this;
  }

  public void unsetDoc() {
    this.doc = null;
  }

  /** Returns true if field doc is set (has been assigned a value) and false otherwise */
  public boolean isSetDoc() {
    return this.doc != null;
  }

  public void setDocIsSet(boolean value) {
    if (!value) {
      this.doc = null;
    }
  }

  public Field getTargetField() {
    return this.targetField;
  }

  public IndexTask setTargetField(Field targetField) {
    this.targetField = targetField;
    return this;
  }

  public void unsetTargetField() {
    this.targetField = null;
  }

  /** Returns true if field targetField is set (has been assigned a value) and false otherwise */
  public boolean isSetTargetField() {
    return this.targetField != null;
  }

  public void setTargetFieldIsSet(boolean value) {
    if (!value) {
      this.targetField = null;
    }
  }

  public void setFieldValue(_Fields field, Object value) {
    switch (field) {
    case TYPE:
      if (value == null) {
        unsetType();
      } else {
        setType((IndexTaskType)value);
      }
      break;

    case DOC:
      if (value == null) {
        unsetDoc();
      } else {
        setDoc((Document)value);
      }
      break;

    case TARGET_FIELD:
      if (value == null) {
        unsetTargetField();
      } else {
        setTargetField((Field)value);
      }
      break;

    }
  }

  public Object getFieldValue(_Fields field) {
    switch (field) {
    case TYPE:
      return getType();

    case DOC:
      return getDoc();

    case TARGET_FIELD:
      return getTargetField();

    }
    throw new IllegalStateException();
  }

  /** Returns true if field corresponding to fieldID is set (has been assigned a value) and false otherwise */
  public boolean isSet(_Fields field) {
    if (field == null) {
      throw new IllegalArgumentException();
    }

    switch (field) {
    case TYPE:
      return isSetType();
    case DOC:
      return isSetDoc();
    case TARGET_FIELD:
      return isSetTargetField();
    }
    throw new IllegalStateException();
  }

  @Override
  public boolean equals(Object that) {
    if (that == null)
      return false;
    if (that instanceof IndexTask)
      return this.equals((IndexTask)that);
    return false;
  }

  public boolean equals(IndexTask that) {
    if (that == null)
      return false;

    boolean this_present_type = true && this.isSetType();
    boolean that_present_type = true && that.isSetType();
    if (this_present_type || that_present_type) {
      if (!(this_present_type && that_present_type))
        return false;
      if (!this.type.equals(that.type))
        return false;
    }

    boolean this_present_doc = true && this.isSetDoc();
    boolean that_present_doc = true && that.isSetDoc();
    if (this_present_doc || that_present_doc) {
      if (!(this_present_doc && that_present_doc))
        return false;
      if (!this.doc.equals(that.doc))
        return false;
    }

    boolean this_present_targetField = true && this.isSetTargetField();
    boolean that_present_targetField = true && that.isSetTargetField();
    if (this_present_targetField || that_present_targetField) {
      if (!(this_present_targetField && that_present_targetField))
        return false;
      if (!this.targetField.equals(that.targetField))
        return false;
    }

    return true;
  }

  @Override
  public int hashCode() {
    List<Object> list = new ArrayList<Object>();

    boolean present_type = true && (isSetType());
    list.add(present_type);
    if (present_type)
      list.add(type.getValue());

    boolean present_doc = true && (isSetDoc());
    list.add(present_doc);
    if (present_doc)
      list.add(doc);

    boolean present_targetField = true && (isSetTargetField());
    list.add(present_targetField);
    if (present_targetField)
      list.add(targetField);

    return list.hashCode();
  }

  @Override
  public int compareTo(IndexTask other) {
    if (!getClass().equals(other.getClass())) {
      return getClass().getName().compareTo(other.getClass().getName());
    }

    int lastComparison = 0;

    lastComparison = Boolean.valueOf(isSetType()).compareTo(other.isSetType());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetType()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.type, other.type);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = Boolean.valueOf(isSetDoc()).compareTo(other.isSetDoc());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetDoc()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.doc, other.doc);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = Boolean.valueOf(isSetTargetField()).compareTo(other.isSetTargetField());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetTargetField()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.targetField, other.targetField);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    return 0;
  }

  public _Fields fieldForId(int fieldId) {
    return _Fields.findByThriftId(fieldId);
  }

  public void read(org.apache.thrift.protocol.TProtocol iprot) throws org.apache.thrift.TException {
    schemes.get(iprot.getScheme()).getScheme().read(iprot, this);
  }

  public void write(org.apache.thrift.protocol.TProtocol oprot) throws org.apache.thrift.TException {
    schemes.get(oprot.getScheme()).getScheme().write(oprot, this);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder("IndexTask(");
    boolean first = true;

    sb.append("type:");
    if (this.type == null) {
      sb.append("null");
    } else {
      sb.append(this.type);
    }
    first = false;
    if (!first) sb.append(", ");
    sb.append("doc:");
    if (this.doc == null) {
      sb.append("null");
    } else {
      sb.append(this.doc);
    }
    first = false;
    if (!first) sb.append(", ");
    sb.append("targetField:");
    if (this.targetField == null) {
      sb.append("null");
    } else {
      sb.append(this.targetField);
    }
    first = false;
    sb.append(")");
    return sb.toString();
  }

  public void validate() throws org.apache.thrift.TException {
    // check for required fields
    // check for sub-struct validity
    if (doc != null) {
      doc.validate();
    }
    if (targetField != null) {
      targetField.validate();
    }
  }

  private void writeObject(java.io.ObjectOutputStream out) throws java.io.IOException {
    try {
      write(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(out)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private void readObject(java.io.ObjectInputStream in) throws java.io.IOException, ClassNotFoundException {
    try {
      read(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(in)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private static class IndexTaskStandardSchemeFactory implements SchemeFactory {
    public IndexTaskStandardScheme getScheme() {
      return new IndexTaskStandardScheme();
    }
  }

  private static class IndexTaskStandardScheme extends StandardScheme<IndexTask> {

    public void read(org.apache.thrift.protocol.TProtocol iprot, IndexTask struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TField schemeField;
      iprot.readStructBegin();
      while (true)
      {
        schemeField = iprot.readFieldBegin();
        if (schemeField.type == org.apache.thrift.protocol.TType.STOP) { 
          break;
        }
        switch (schemeField.id) {
          case 1: // TYPE
            if (schemeField.type == org.apache.thrift.protocol.TType.I32) {
              struct.type = liker.IndexTaskType.findByValue(iprot.readI32());
              struct.setTypeIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 2: // DOC
            if (schemeField.type == org.apache.thrift.protocol.TType.STRUCT) {
              struct.doc = new Document();
              struct.doc.read(iprot);
              struct.setDocIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 3: // TARGET_FIELD
            if (schemeField.type == org.apache.thrift.protocol.TType.STRUCT) {
              struct.targetField = new Field();
              struct.targetField.read(iprot);
              struct.setTargetFieldIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          default:
            org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
        }
        iprot.readFieldEnd();
      }
      iprot.readStructEnd();

      // check for required fields of primitive type, which can't be checked in the validate method
      struct.validate();
    }

    public void write(org.apache.thrift.protocol.TProtocol oprot, IndexTask struct) throws org.apache.thrift.TException {
      struct.validate();

      oprot.writeStructBegin(STRUCT_DESC);
      if (struct.type != null) {
        oprot.writeFieldBegin(TYPE_FIELD_DESC);
        oprot.writeI32(struct.type.getValue());
        oprot.writeFieldEnd();
      }
      if (struct.doc != null) {
        oprot.writeFieldBegin(DOC_FIELD_DESC);
        struct.doc.write(oprot);
        oprot.writeFieldEnd();
      }
      if (struct.targetField != null) {
        oprot.writeFieldBegin(TARGET_FIELD_FIELD_DESC);
        struct.targetField.write(oprot);
        oprot.writeFieldEnd();
      }
      oprot.writeFieldStop();
      oprot.writeStructEnd();
    }

  }

  private static class IndexTaskTupleSchemeFactory implements SchemeFactory {
    public IndexTaskTupleScheme getScheme() {
      return new IndexTaskTupleScheme();
    }
  }

  private static class IndexTaskTupleScheme extends TupleScheme<IndexTask> {

    @Override
    public void write(org.apache.thrift.protocol.TProtocol prot, IndexTask struct) throws org.apache.thrift.TException {
      TTupleProtocol oprot = (TTupleProtocol) prot;
      BitSet optionals = new BitSet();
      if (struct.isSetType()) {
        optionals.set(0);
      }
      if (struct.isSetDoc()) {
        optionals.set(1);
      }
      if (struct.isSetTargetField()) {
        optionals.set(2);
      }
      oprot.writeBitSet(optionals, 3);
      if (struct.isSetType()) {
        oprot.writeI32(struct.type.getValue());
      }
      if (struct.isSetDoc()) {
        struct.doc.write(oprot);
      }
      if (struct.isSetTargetField()) {
        struct.targetField.write(oprot);
      }
    }

    @Override
    public void read(org.apache.thrift.protocol.TProtocol prot, IndexTask struct) throws org.apache.thrift.TException {
      TTupleProtocol iprot = (TTupleProtocol) prot;
      BitSet incoming = iprot.readBitSet(3);
      if (incoming.get(0)) {
        struct.type = liker.IndexTaskType.findByValue(iprot.readI32());
        struct.setTypeIsSet(true);
      }
      if (incoming.get(1)) {
        struct.doc = new Document();
        struct.doc.read(iprot);
        struct.setDocIsSet(true);
      }
      if (incoming.get(2)) {
        struct.targetField = new Field();
        struct.targetField.read(iprot);
        struct.setTargetFieldIsSet(true);
      }
    }
  }

}

