/**
 * Autogenerated by Thrift Compiler (0.9.3)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package liker;


import java.util.Map;
import java.util.HashMap;
import org.apache.thrift.TEnum;

public enum IndexTaskType implements org.apache.thrift.TEnum {
  Add(1),
  Update(0),
  Delete(-1);

  private final int value;

  private IndexTaskType(int value) {
    this.value = value;
  }

  /**
   * Get the integer value of this enum value, as defined in the Thrift IDL.
   */
  public int getValue() {
    return value;
  }

  /**
   * Find a the enum type by its integer value, as defined in the Thrift IDL.
   * @return null if the value is not found.
   */
  public static IndexTaskType findByValue(int value) { 
    switch (value) {
      case 1:
        return Add;
      case 0:
        return Update;
      case -1:
        return Delete;
      default:
        return null;
    }
  }
}
