/**
 * Autogenerated by Thrift Compiler (0.9.3)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package liker;


import java.util.Map;
import java.util.HashMap;
import org.apache.thrift.TEnum;

public enum ResponseCode implements org.apache.thrift.TEnum {
  UnknowErr(500),
  Success(200);

  private final int value;

  private ResponseCode(int value) {
    this.value = value;
  }

  /**
   * Get the integer value of this enum value, as defined in the Thrift IDL.
   */
  public int getValue() {
    return value;
  }

  /**
   * Find a the enum type by its integer value, as defined in the Thrift IDL.
   * @return null if the value is not found.
   */
  public static ResponseCode findByValue(int value) { 
    switch (value) {
      case 500:
        return UnknowErr;
      case 200:
        return Success;
      default:
        return null;
    }
  }
}
